### ISSUE TITLE
pure -a throw error

### ISSUE THREAD

**Issue by zhaihaoran** [ufologist/puer-mock#12]
package.json
`puer -a _mockserver-config.js`

当我执行这段命令，会报 “unknow  option -a“ ，puer -h 里查看，确实也查不到-a的后缀命令。
但看puer的官网example上也是有-a的例子，求帮助

**Comment by ufologist** [comment]
刚去看了一下 npm 上 puer 的版本, 由于作者已经发布了 `2.0.0` 版本, 所以你默认安装的 puer 是 `2.x` 版本, 而 puer-mock 是基于 `puer@1.x` 版本的扩展, 依赖 `puer@1.x`

因此你只需要卸载 puer 之后, 再安装 `puer@1.x` 版本即可

```
npm uninstall puer -g
npm install puer@1.x -g
```

**Comment by zhaihaoran** [comment]
您好，我这边能正常启动了，但是依旧拿不到数据啊

**现象**：
/api/users  ----   Cannot GET /api/users
/_apidoc.html  ----  同样也是 Cannot GET /_apidoc.html
/   ----   正常显示列表目录

**_mockserver.json**
`{
    "api": {
        "GET /api/users": {
            "response": {
                "status": 0,
                "data": {
                    "name": "box"
                }
            }
        }
    }
}
`
**package.json**
`"mock": "puer -a _mockserver.json -p 3333"`

是我哪里有问题吗？求助

环境

window 64位

nodejs 9.2.0

**Comment by ufologist** [comment]
@zhaihaoran 启动的方式不对啊, 请看文档

```
puer -a _mockserver.js
```

**Comment by zhaihaoran** [comment]
已经解决了，非常好用
