### ISSUE TITLE
Node v10.15.1环境下修改配置文件报错

### ISSUE THREAD

**Issue by yibhou** [ufologist/puer-mock#15]
fs.js:137
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:137:11)
    at Object.utimes (fs.js:1090:14)
    at /mnt/h/Projects/waper/subject.waper.com/node_modules/puer-mock/src/puer-mock.js:34:12
    at StatWatcher.<anonymous> (/mnt/h/Projects/waper/subject.waper.com/node_modules/puer-mock/src/util.js:25:24)
    at StatWatcher.emit (events.js:189:13)
    at StatWatcher.onchange (internal/fs/watchers.js:50:8)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! subject.waper.com@1.0.0 mockServer: `npx puer -p 9090 -r puer/puerfile.js "puer/config.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the subject.waper.com@1.0.0 mockServer script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/richard/.npm/_logs/2019-02-20T09_08_28_867Z-debug.log

**Comment by yibhou** [comment]
fs.utimes 要改成同步的fs.utimesSync才行

**Comment by yibhou** [comment]
麻烦修复一下

**Comment by ufologist** [comment]
`1.2.4` 版本已经修复

**Comment by yibhou** [comment]
@ufologist   log信息没有去掉
![image](https://user-images.githubusercontent.com/10102594/53148780-beb82480-35e6-11e9-8f02-2bada05610aa.png)
