### ISSUE TITLE
Feature request: support multiple _mockserver.json files

### ISSUE THREAD

**Issue by liudanking** [ufologist/puer-mock#2]
`puer-mock` is the one I am looking for.

I have multiple micro services. And I would like to generate one _mockserver.json file for each service. 

Can puer-mock support this mode?

**Comment by ufologist** [comment]
@liudanking you have multiple micro services, and would you generate a `_mockserver.json` for each, and finally merge into a single `_mockserver.json`?

**Comment by liudanking** [comment]
I would like to generate a `_mockserver-SERVCIE-NAME.json` for each micro service, and I do NOT want to merge these files into one `_mockserver.json`.
I would like put all these `_mockserver-SERVCIE-NAME.json` to a directory, e.g., `json.d`, then puer-mock detects and serve all these files in  `json.d`. 

Is this possile?

**Comment by ufologist** [comment]
thanks @liudanking 's suggestion.

If your want support multiple `_mockserver.json` files, you would try to customize `_mockserver.js`.
Because you can get `routeConfig` here, so you would do some thing with it for yourself.

**before puer-mock@1.2.0**

The easy way:

``` javascript
var puerMock = require('puer-mock');
// TODO you would list all .json files here...
var routeConfig1 = puerMock(__filename, './_mockserver1.json');
var routeConfig2 = puerMock(__filename, './_mockserver2.json');
// merge config and then exports
module.exports = Object.assign(routeConfig1, routeConfig2);
```

**note: `/_apidoc` route will be overwrite, it only get the last routeConfig info.**

Please see [puer-mock.js](https://github.com/ufologist/puer-mock/blob/master/src/puer-mock.js#L34) and [puer](https://github.com/leeluolee/puer/blob/master/src/index.coffee#L149) for more info.

so you should redefine `/_apidoc` route.

```javascript
var puerMock = require('puer-mock');
var util = require('puer-mock/src/util.js');
var rc = require('puer-mock/src/route-config.js');

var mockFiles = ['./_mockserver-event.json', './_mockserver-user.json'];

// 合并所有的路由配置
function getRouteConfig(mockFiles) {
    return mockFiles.reduce(function(previous, mockFile) {
        return Object.assign(previous, puerMock(__filename, mockFile));
    }, {});
}

// 重新定义 _apidoc 路由
function redefineApidocRoute(mockFiles, routeConfig) {
    // 重新读取所有的 mockserver 配置文件
    // 追加每个 mockserver.json#api 的配置
    var mockConfig = mockFiles.reduce(function(previous, mockFile) {
        var thisMockConfig = rc.getMockConfig(mockFile);

        // 先合并属性
        for (var propertyName in thisMockConfig) {
            if (!previous[propertyName]) {
                previous[propertyName] = thisMockConfig[propertyName];
            }
        }
        // 再单独合并 mockserver.json#api 这个嵌套的属性
        previous.api = Object.assign(previous.api, thisMockConfig.api);
        return previous;
    }, {});

    var groupMockConfig = util.groupApiByModuleName(mockConfig);

    routeConfig['GET /_apidoc'] = function(request, response, next) {
        // puer-mock.js#appendApidocRoute
        response.set(util.CORS_HEADER);
        response.jsonp(groupMockConfig);
    };
}

var routeConfig = getRouteConfig(mockFiles);
redefineApidocRoute(mockFiles, routeConfig);

module.exports = routeConfig;
```

**Comment by ufologist** [comment]
**after puer-mock@1.2.2** support `.js` mock config

```javascript
module.exports = require('puer-mock')(__filename, './_mockserver-config.js');
```

or try [mock-http-api](https://github.com/ufologist/mock-http-api) support multiple mock config
