### ISSUE TITLE
安装完puer -mock 按教程使用，会报如下的错

### ISSUE THREAD

**Issue by Xiecai** [ufologist/puer-mock#4]
![qq 20160831154045](https://cloud.githubusercontent.com/assets/3449375/18120275/543b909c-6f91-11e6-9242-e4bd5fba5c6d.jpg)

**Comment by ufologist** [comment]
@Xiecai 看你的说明, 已经成功安装了 `puer`, `puer` 跑起来也没有问题.

请确认 `puer-mock` 模块是否安装成功

```
npm install puer-mock
```

**Comment by Xiecai** [comment]
您看，我这确实是安装好了，_mockserver.js与_mockserver.json都是用的默认的：
![1](https://cloud.githubusercontent.com/assets/3449375/18153314/43a39894-702f-11e6-9f09-3b0d7744f281.jpg)
![2](https://cloud.githubusercontent.com/assets/3449375/18153318/472ea15c-702f-11e6-8a09-eac21775e623.jpg)
![3](https://cloud.githubusercontent.com/assets/3449375/18153319/4abe1410-702f-11e6-8a32-86373fb6bea8.jpg)
![4](https://cloud.githubusercontent.com/assets/3449375/18153354/8839d7ac-702f-11e6-9951-fde9454f8f45.jpg)

**Comment by ufologist** [comment]
@Xiecai **你安装 puer-mock 的位置和你的项目是在同一个地方吗?**

从这张图中, 我在你的项目目录下都没有看见 `node_modules` 目录
![](https://cloud.githubusercontent.com/assets/3449375/18153319/4abe1410-702f-11e6-8a32-86373fb6bea8.jpg)

这点在我文档中这里没有说清楚, 是需要**在你项目的目录下去安装 `puer-mock` 的**

```
cd yourprojectdir
npm intall puer-mock
```

非常感谢你的反馈, 我会在文档中说明这一点

**Comment by Xiecai** [comment]
确实是这个问题，现在好了
