### ISSUE TITLE
能否添加支持指定json文件的方法

### ISSUE THREAD

**Issue by jing2si** [ufologist/puer-mock#5]
能否添加支持指定json文件的方法，类似下面这样，不一定非要是_mockserver.json。

``` javascript
puer-mock xxx.json
```

**Comment by ufologist** [comment]
是有提供这个功能的, 在 [example/_mockserver.js](https://github.com/ufologist/puer-mock/blob/master/example/_mockserver.js) 文件中有说明, 但是忘记在文档中说了.

现在已经补充到 [README](https://github.com/ufologist/puer-mock) 文档中了.

指定 json 文件的方法如下

``` javascript
// use _mockserver2.json for config file
//
// _mockserver.js
// puer -a _mockserver.js
module.exports = require('puer-mock')(__filename, './_mockserver2.json');
```
