### ISSUE TITLE
能否用 js 写 mockserve.json?

### ISSUE THREAD

**Issue by zhaozhe0831** [ufologist/puer-mock#6]
主要想法是 想  用多个 js 文件，来作为 mock 的 template 模板。
之后，再统一引用到 mockserver.json 文件中，
把 mockserver.json 的文件格式变成 js 的话，就可以对象的形式引用 mock template 的 js 模板文件了。

表达的可能不太清楚，盼回复。谢谢。

**Comment by ufologist** [comment]
@zhaozhe0831 对你的问题有点不知所措, 请举个例子吧

我想提一下的就是, `puer-mock` 仅仅是解析了`_mockserver.json` 文件的规则, 然后设置路由而已, 如果你想完全抛开 `_mockserver.json` 都是可以的, 或者你可以预先动态生成 `_mockserver.json`, 再启动 `puer-mock`, 都是完全可以的

```javascript
// _mockserver.js
var puerMock = require('puer-mock');
var routeConfig = puerMock();
// 其实你完全可以这样来玩, 在这里接着定义 route 即可, 发挥你的想象力
// 例如定义一个常用的 500 接口, 来测试服务器报错的情况
routeConfig['GET /500'] = function(request, response, next) {
    response.status(500).end();
};
module.exports = routeConfig;
```

**Comment by jivinliu** [comment]
这位朋友的意思应该是想对mockserver.json进行拆分，一个大点的项目几十上百个接口放一个文件，不利于维护

**Comment by ghost** [comment]
同意这个观点，目前尝试在公司项目中加上这个mock作为后端替代，但是发现，后端接口太多，全部写在一个json中比较难以维护，我也一直在想能否进行json的拆分，今天刚好看到这个issue

**Comment by ufologist** [comment]
@jivinliu @GuoJohnny 
puer-mock 的接口配置文件 `_mockserver.json` 本身有[分组的功能](https://github.com/ufologist/puer-mock/blob/master/_mockserver-config.md): `"module": "接口分组"`, 编辑接口的时候一般很少冲突, 但确实不排除所有接口在一个很大的文件中编辑, 会让冲突的概率提升很多, 我们一般考虑定接口的时候按照模块划分, 这样可以减少冲突.

如果是想对 `_mockserver.json` 做拆分, 可以参考
[Feature request: support multiple _mockserver.json files](https://github.com/ufologist/puer-mock/issues/2)

**Comment by ghost** [comment]
十分感谢指导，正好能用上
