### ISSUE TITLE
can not run as you say

### ISSUE THREAD

**Issue by LuoHuacheng** [ufologist/puer-mock#8]
I did as you said step by step, but the result isn,t same as yours.
![snip20170227_1](https://cloud.githubusercontent.com/assets/14214871/23366690/97d69b3c-fd42-11e6-8057-ec9fff957959.png)
![snip20170227_2](https://cloud.githubusercontent.com/assets/14214871/23366738/d0c2f7d8-fd42-11e6-88f3-53ee20e2a95a.png)

**Comment by ufologist** [comment]
* do you **copy node_modules/puer-mock/example files to your project root directory**?
* what about your nodejs version? **please try `node 6.x`**

**Comment by LuoHuacheng** [comment]
thank you for your answer. I updated my node to v7.x first, it didn't run. Then I installed node v6.10, it Worked.
![snip20170228_2](https://cloud.githubusercontent.com/assets/14214871/23396542/3e768d4e-fdcf-11e6-8fbe-dc60ea54f5fd.png)

**Comment by ufologist** [comment]
@BoothLuo you are welcome.

It all OK now? No error anymore, and `puer-mock` worked?
You can try config your mock api now?

**Comment by LuoHuacheng** [comment]
yes, it works very well. I'm trying my mock api now and you can close this issue. And thank you again for helping me.
