### ISSUE TITLE
一些疑问？

### ISSUE THREAD

**Issue by henryzp** [ufologist/puer-mock#9]
就是我司后台用的是swagger。

然后怎么结合这个mock server？

文档里面提及的sosoapi，具体是做什么的？因为对于后台来说，文档已经生成了，不需要手动再编写一份了吧？

**Comment by ufologist** [comment]
@henryzp 你是说你们后端是通过 swagger 来作为接口文档的? 也就是说你们已经有了一份 `swagger.json` 的接口配置文件? 现在是想通过 `puer-mock` 来解析 swagger 的接口定义规则来做一个 mock server 吗?

另外就是你提到的 sosoapi, 这是一个第三方的服务, 和 `puer-mock` 没有任何关系, 如果你想了解, 请到他们的网站去了解

**Comment by henryzp** [comment]
@ufologist ，对。。可以做到通过 puer-mock 来解析 swagger 的接口定义规则来做一个 mock server 吗？

另外我们后端给的是一个index.html访问地址，就是打开能看到所有的请求链接

**Comment by ufologist** [comment]
@henryzp 理论上可以做到通过 puer-mock 来解析 swagger 的接口定义规则
即在 `_mockserver.js` 中读取 swagger.json 文件, 然后根据他的规则, 转换成 `_mockserver.json` 需要的格式即可.

具体转换规则, 我没有做过, 不过仅仅是 JSON 文件的解析而已, 应该问题不大, 主要是理解 swagger.json 的配置项, 找出与 `_mockserver.json` 的配置项对应的关系, 即 swagger.json 的配置项如何放入到 `_mockserver.json` 的配置项中
例如:
* swagger.json#info.title -> `_mockserver.json`#info.summary
* swagger.json#paths -> `_mockserver.json`#api

关于
> 后端给的是一个index.html访问地址，就是打开能看到所有的请求链接

在 `puer-mock` 启动后你默认可以通过 `/_apidoc.html` 来查看接口文档, 但这个页面你是完全可以自定义的.
